#!/group_workspaces/jasmin2/ncas_radar/software/anaconda2/bin/python

import pandas as pd

df = pd.read_csv("../source/input", error_bad_lines=False)
exidfr=pd.DataFrame()
df1=df[['TheTime','ozone_4','ozone_2']]
print(df1)
df1.to_csv('../target/output', encoding='utf-8', index=False)
